name: tessera
description: "Offline math solver with step-by-step explanations."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.8
  flutter_bloc: any
  get_it: any
  injectable: any
  go_router: any
  hive: any
  hive_flutter: any
  flutter_math_fork: ^0.7.4
  flutter_js: any
  google_mlkit_text_recognition: any
  tflite_flutter: any
  freezed_annotation: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: any
  build_runner: any
  freezed: any
  injectable_generator: any
  hive_generator: any

dependency_overrides:
  clavier:
    path: ./clavier

flutter:
  uses-material-design: true
  assets:
    - assets/js/
    - assets/fonts/
